"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useState } from "react";
import CreatePosts from "./create-post/page";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

function throwError() { }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [showCreateForm, setShowCreateForm] = useState(false);

  const openForm = () => {
    setShowCreateForm(true);
};

const closeForm = () => {
    setShowCreateForm(false);
};

  const header = (
    <header>
      <nav className="bg-gray-600 p-4">
        <div className="container mx-auto flex items-center justify-between">
          <a href="#" className="text-white text-lg font-semibold">
            Blog Site
          </a>

          <div className="flex space-x-4">
            <a href="/" className="text-gray-300 hover:text-white">
              Home
            </a>
            <div>
              {/* <a href="#" className="text-gray-300 hover:text-white"> */}
              <a
                className="cursor-pointer has-tooltip relative text-gray-300 hover:text-white"
                onClick= {openForm}//{() => setShowCreateForm(true)}
              >
                Create blog
                {/* <span className="tooltip left-0 top-[100%]   rounded shadow-lg bg-gray-100 text-red-500 mt-2 p-2 w-[250px]">
                  Feature not implemented
                </span> */}
              </a>
              {showCreateForm && <CreatePosts onClose={closeForm}/>}
            </div>

            <a
              href="#"
              className=" has-tooltip relative text-gray-300 hover:text-white"
            >
              Services
              <span className="tooltip left-0 top-[100%]   rounded shadow-lg p-2 w-[250px] bg-gray-100 text-red-500 mt-2 ">
                Feature not implemented
              </span>
            </a>
            <a
              href="#"
              className="has-tooltip relative text-gray-300 hover:text-white"
            >
              Contact{" "}
              <span className="tooltip left-0 top-[100%]   rounded shadow-lg p-2 w-[250px] bg-gray-100 text-red-500 mt-2 ">
                Feature not implemented
              </span>
            </a>
          </div>
        </div>
      </nav>
    </header>
  );

  const footer = (
    <footer>
      <div className="border-t border-slate-400 mt-12 py-50 text-center text-slate-400 bg-gray-600 p-4">
        <h3>developed by Sagar Bana. Copyright @ 2024</h3>
      </div>
    </footer>
  );

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mx-auto  max-w-2xl px-6">
          {header}
          {children}
          {footer}
        </div>
      </body>
    </html>
  );
}
